// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Class is the predicate function for class builders.
type Class func(*sql.Selector)

// Department is the predicate function for department builders.
type Department func(*sql.Selector)

// Staff is the predicate function for staff builders.
type Staff func(*sql.Selector)

// Student is the predicate function for student builders.
type Student func(*sql.Selector)
